stages:
  - lint
  - test

variables:
  NODE_VERSION: "18"

cache:
  key: ${CI_COMMIT_REF_SLUG}-node-modules
  paths:
    - node_modules/

lint:
  stage: lint
  image: node:$NODE_VERSION
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules/
  script:
    - npm ci
    - npx eslint .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_BRANCH == "practice" || $CI_COMMIT_BRANCH == "main"'
      changes:
        - "**/*.js"

test:
  stage: test
  image: node:$NODE_VERSION
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules/
  script:
    - npm ci
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    - if: '$CI_COMMIT_BRANCH == "practice" || $CI_COMMIT_BRANCH == "main"'
      changes:
        - "**/*.js"