stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules/
  script:
    - npm ci
    - npx eslint .
  only:
    refs:
      - practice
      - main
      - merge_requests
    changes:
      - "**/*.js"

test:
  stage: test
  image: node:18
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node-modules
    paths:
      - node_modules/
  script:
    - npm ci
    - npm test
  only:
    refs:
      - practice
      - main
      - merge_requests
    changes:
      - "**/*.js"